#pragma once

#ifndef FW_VERSION
#define FW_VERSION "0.0.0"
#endif

#ifndef CONFIG_DEFAULT_WHEEL_CIRCUM_MM
#define CONFIG_DEFAULT_WHEEL_CIRCUM_MM 2105
#endif

#ifndef CONFIG_DEFAULT_MAGNETS_PER_REV
#define CONFIG_DEFAULT_MAGNETS_PER_REV 1
#endif

#ifndef CONFIG_DEFAULT_HALL_PIN
#define CONFIG_DEFAULT_HALL_PIN 4
#endif

#define CONFIG_WHEEL_CIRCUMF_MM CONFIG_DEFAULT_WHEEL_CIRCUM_MM
#define CONFIG_MAGNETS_PER_REV  CONFIG_DEFAULT_MAGNETS_PER_REV
#define CONFIG_HALL_PIN         CONFIG_DEFAULT_HALL_PIN


